/**
 * This module was automatically generated by `ts-interface-builder`
 */
import * as t from "ts-interface-checker";
// tslint:disable:object-literal-key-quotes

export const Workflow = t.iface([], {
  "template_version": "string",
  "workflow_name": "string",
  "workflow_description": "string",
  "steps": t.tuple("Step", t.rest(t.array("Step"))),
});

export const Step = t.iface([], {
  "chain_id": "string",
  "to": t.opt("string"),
  "value": t.opt("string"),
  "data": t.opt("string"),
  "description": "string",
});

const exportedTypeSuite: t.ITypeSuite = {
  Workflow,
  Step,
};
export default exportedTypeSuite;
